name: Nested Test - Hello World

on:
  workflow_call:
    inputs:
      message:
        description: "Input message string to log"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout flyingdarts/flyingdarts
        uses: actions/checkout@v4
        with:
          repository: flyingdarts/flyingdarts
          path: ./flyingdarts
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Hello World Log
        run: |
          echo "Hello World!"
          echo "Input message: ${{ inputs.message }}"
